# 支付：Waffo Pancake（main-Waffo）
# 密钥 / 产品 ID / Resend：Dokploy「Environment」+ Build Arguments 注入（与 EditStamp 一致需含 RESEND_*）
# NEXT_PUBLIC_* 需 Build Arguments（客户端内联）
# ========== 阶段 1：安装依赖 ==========
FROM node:20-alpine AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm config set fetch-retries 5 \
    && npm config set fetch-retry-mintimeout 20000 \
    && npm config set fetch-retry-maxtimeout 120000 \
    && npm config set fetch-timeout 600000 \
    && npm ci --legacy-peer-deps

# ========== 阶段 2：构建 ==========
# 在 Dokploy 的 Build-time Arguments 里填写以下变量即可生效（如 NEXT_PUBLIC_GOOGLE_ANALYTICS_ID=G-MJP605Q6WY）
FROM node:20-alpine AS builder
ARG NEXT_PUBLIC_SITE_URL
ARG NEXT_PUBLIC_BASE_URL
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG NEXT_PUBLIC_GOOGLE_ANALYTICS_ID
ARG NEXT_PUBLIC_ANALYTICS_DOMAIN
ARG NEXT_PUBLIC_ANALYTICS_SRC
ARG BETTER_AUTH_SECRET
ARG DB_HOST
ARG DB_PORT
ARG DB_USER
ARG DB_PASSWORD
ARG DB_NAME
ARG WAFFO_MERCHANT_ID
ARG WAFFO_STORE_ID
ARG WAFFO_PRIVATE_KEY
ARG WAFFO_ENVIRONMENT
ARG WAFFO_PRICE_ID_PRO_MONTHLY
ARG WAFFO_PRICE_ID_PRO_YEARLY
ARG WAFFO_PRICE_ID_PRO_MONTHLY_ONETIME
ARG WAFFO_PRICE_ID_PRO_YEARLY_ONETIME
ARG RESEND_API_KEY
ARG RESEND_FROM_EMAIL
ENV NEXT_TELEMETRY_DISABLED=1
ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL
ENV NEXT_PUBLIC_BASE_URL=$NEXT_PUBLIC_BASE_URL
ENV GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
ENV GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
ENV NEXT_PUBLIC_GOOGLE_ANALYTICS_ID=$NEXT_PUBLIC_GOOGLE_ANALYTICS_ID
ENV NEXT_PUBLIC_ANALYTICS_DOMAIN=$NEXT_PUBLIC_ANALYTICS_DOMAIN
ENV NEXT_PUBLIC_ANALYTICS_SRC=$NEXT_PUBLIC_ANALYTICS_SRC
ENV BETTER_AUTH_SECRET=$BETTER_AUTH_SECRET
ENV DB_HOST=$DB_HOST
ENV DB_PORT=$DB_PORT
ENV DB_USER=$DB_USER
ENV DB_PASSWORD=$DB_PASSWORD
ENV DB_NAME=$DB_NAME
ENV WAFFO_MERCHANT_ID=$WAFFO_MERCHANT_ID
ENV WAFFO_STORE_ID=$WAFFO_STORE_ID
ENV WAFFO_PRIVATE_KEY=$WAFFO_PRIVATE_KEY
ENV WAFFO_ENVIRONMENT=$WAFFO_ENVIRONMENT
ENV WAFFO_PRICE_ID_PRO_MONTHLY=$WAFFO_PRICE_ID_PRO_MONTHLY
ENV WAFFO_PRICE_ID_PRO_YEARLY=$WAFFO_PRICE_ID_PRO_YEARLY
ENV WAFFO_PRICE_ID_PRO_MONTHLY_ONETIME=$WAFFO_PRICE_ID_PRO_MONTHLY_ONETIME
ENV WAFFO_PRICE_ID_PRO_YEARLY_ONETIME=$WAFFO_PRICE_ID_PRO_YEARLY_ONETIME
# 与 EditStamp 一致：构建期写入，避免 Next standalone 把未定义的 RESEND_* 打成 undefined
ENV RESEND_API_KEY=$RESEND_API_KEY
ENV RESEND_FROM_EMAIL=$RESEND_FROM_EMAIL
# Next.js only inlines NEXT_PUBLIC_* into the client bundle — map from WAFFO_PRICE_ID_*
ENV NEXT_PUBLIC_WAFFO_PRICE_ID_PRO_MONTHLY=$WAFFO_PRICE_ID_PRO_MONTHLY
ENV NEXT_PUBLIC_WAFFO_PRICE_ID_PRO_YEARLY=$WAFFO_PRICE_ID_PRO_YEARLY
ENV NEXT_PUBLIC_WAFFO_PRICE_ID_PRO_MONTHLY_ONETIME=$WAFFO_PRICE_ID_PRO_MONTHLY_ONETIME
ENV NEXT_PUBLIC_WAFFO_PRICE_ID_PRO_YEARLY_ONETIME=$WAFFO_PRICE_ID_PRO_YEARLY_ONETIME
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

# ========== 阶段 3：运行（standalone 输出，体积小） ==========
# 运行时密钥（DB / Waffo / Resend 等）由 Dokploy Environment / Build Args 注入
FROM node:20-alpine AS runner
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG BETTER_AUTH_SECRET
ARG DB_HOST
ARG DB_PORT
ARG DB_USER
ARG DB_PASSWORD
ARG DB_NAME
ARG WAFFO_MERCHANT_ID
ARG WAFFO_STORE_ID
ARG WAFFO_PRIVATE_KEY
ARG WAFFO_ENVIRONMENT
ARG WAFFO_PRICE_ID_PRO_MONTHLY
ARG WAFFO_PRICE_ID_PRO_YEARLY
ARG WAFFO_PRICE_ID_PRO_MONTHLY_ONETIME
ARG WAFFO_PRICE_ID_PRO_YEARLY_ONETIME
ARG RESEND_API_KEY
ARG RESEND_FROM_EMAIL
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
ENV GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
ENV BETTER_AUTH_SECRET=$BETTER_AUTH_SECRET
ENV DB_HOST=$DB_HOST
ENV DB_PORT=$DB_PORT
ENV DB_USER=$DB_USER
ENV DB_PASSWORD=$DB_PASSWORD
ENV DB_NAME=$DB_NAME
ENV WAFFO_MERCHANT_ID=$WAFFO_MERCHANT_ID
ENV WAFFO_STORE_ID=$WAFFO_STORE_ID
ENV WAFFO_PRIVATE_KEY=$WAFFO_PRIVATE_KEY
ENV WAFFO_ENVIRONMENT=$WAFFO_ENVIRONMENT
ENV WAFFO_PRICE_ID_PRO_MONTHLY=$WAFFO_PRICE_ID_PRO_MONTHLY
ENV WAFFO_PRICE_ID_PRO_YEARLY=$WAFFO_PRICE_ID_PRO_YEARLY
ENV WAFFO_PRICE_ID_PRO_MONTHLY_ONETIME=$WAFFO_PRICE_ID_PRO_MONTHLY_ONETIME
ENV WAFFO_PRICE_ID_PRO_YEARLY_ONETIME=$WAFFO_PRICE_ID_PRO_YEARLY_ONETIME
ENV RESEND_API_KEY=$RESEND_API_KEY
ENV RESEND_FROM_EMAIL=$RESEND_FROM_EMAIL
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# 使用 standalone 时，静态与 public 需单独复制（public 放最后，避免被 standalone 覆盖）
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=builder --chown=nextjs:nodejs /app/public ./public

# 复制 sharp 及其依赖（standalone 图片优化需要）
COPY --from=builder /app/node_modules/sharp ./node_modules/sharp
COPY --from=builder /app/node_modules/@img ./node_modules/@img

USER nextjs
EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"
CMD ["node", "server.js"]
